### ISSUE TITLE
Bug: not refreshing value from configmap

### ISSUE THREAD

**Issue by venkatamutyala** [jkroepke/helm-kubectl#2]
So i got the happy path example working where I can fetch a value and it appears to get rendered as expected in argocd but if i change the value in the configmap how do i get argocd to pick up the new value?

**Comment by jkroepke** [comment]
This is not a bug, this is a expected behavior. Any change on that configmap requires a hard refresh inside ArgoCD (go to your Application and take a note on the arrow at the refresh button).


Background:

> argocd-repo-server Every 3m (by default) Argo CD checks for changes to the app manifests. Argo CD assumes by default that manifests only change when the repo changes, so it caches generated manifests (for 24h by default). With Kustomize remote bases, or Helm patch releases, the manifests can change even though the repo has not changed. By reducing the cache time, you can get the changes without waiting for 24h. Use --repo-cache-expiration duration, and we'd suggest in low volume environments you try '1h'. Bear in mind this will negate the benefit of caching if set too low.

https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/

To solve this long-term, you have to lower your cache ttl.

**Comment by venkatamutyala** [comment]
thanks!
